# Generated by Django 2.2.14 on 2020-07-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200730_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coupon',
        ),
    ]
