# Generated by Django 2.2.14 on 2020-07-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_coupon'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchases',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Coupon'),
        ),
    ]
