# Generated by Django 2.2.14 on 2020-08-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_userpurchases_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchases',
            name='in_use',
            field=models.BooleanField(default=0),
        ),
    ]
