# Generated by Django 3.0.6 on 2020-06-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorcallrequest',
            old_name='mentor_type',
            new_name='product',
        ),
    ]
