# Generated by Django 3.0.6 on 2020-06-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestedschedules',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
