# Generated by Django 3.0.7 on 2020-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchases',
            old_name='users',
            new_name='user',
        ),
    ]
