# Generated by Django 3.0.7 on 2020-06-19 08:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcallschedule',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='acceptedcallschedule',
            name='channel',
            field=models.CharField(default=accounts.models.channel_gen, max_length=255),
        ),
    ]
