# Generated by Django 3.0.7 on 2020-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200620_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpaytransactions',
            old_name='timestamp',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='userpurchases',
            name='payment_progress',
            field=models.BooleanField(default=1),
        ),
    ]
