# Generated by Django 3.0.6 on 2020-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200616_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorcallrequest',
            name='closed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='mentorcallrequest',
            name='scheduled',
            field=models.BooleanField(default=0),
        ),
    ]
