# Generated by Django 3.0.7 on 2020-06-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200623_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='associated_product',
        ),
        migrations.CreateModel(
            name='MentorProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MentorProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MentorProfile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Product')),
            ],
        ),
    ]
