# Generated by Django 3.0.6 on 2020-06-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200616_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedcallschedule',
            old_name='token',
            new_name='channel',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='mentor_channel',
        ),
    ]
