# Generated by Django 3.0.7 on 2020-06-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200620_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaytransactions',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
