# Generated by Django 3.0.7 on 2020-06-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200628_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorproducts',
            old_name='MentorProfile',
            new_name='mentor',
        ),
    ]
