# Generated by Django 3.0.7 on 2020-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200628_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_type',
            field=models.CharField(default='O', max_length=2),
        ),
    ]
