# Generated by Django 3.0.7 on 2020-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200628_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='mentorcallrequest',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
