# Generated by Django 3.0.7 on 2020-06-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_active'),
        ('accounts', '0008_auto_20200628_2256'),
    ]

    operations = [
    ]
