# Generated by Django 3.0.7 on 2020-06-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20200629_0119'),
        ('accounts', '0009_merge_20200629_0142'),
    ]

    operations = [
    ]
