# Generated by Django 3.0.7 on 2020-06-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200629_1626'),
        ('accounts', '0010_merge_20200629_1412'),
    ]

    operations = [
    ]
