# Generated by Django 3.0.7 on 2020-06-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20200629_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorcallrequest',
            name='report_submitted',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='FinalMentorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('findings', models.CharField(blank=True, max_length=255, null=True)),
                ('suggestions', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedule', to='accounts.MentorCallRequest')),
            ],
        ),
    ]
