# Generated by Django 3.0.7 on 2020-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200701_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmentorreport',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalmentorreport',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalmentorreport',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalmentorreport',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalmentorreport',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
