# Generated by Django 3.0.7 on 2020-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200704_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmentorreport',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
