# Generated by Django 3.0.7 on 2020-07-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200712_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorproducts',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
    ]
