# Generated by Django 3.0.7 on 2020-07-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        ('accounts', '0017_auto_20200713_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedschedules',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.MentorProfile'),
        ),
        migrations.DeleteModel(
            name='MentorProducts',
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
