# Generated by Django 3.0.7 on 2020-07-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200713_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userredeemcoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='userredeemcoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='UserRedeemCoupon',
        ),
    ]
