# Generated by Django 2.2.14 on 2020-10-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
