# Generated by Django 2.2.14 on 2020-07-21 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmitReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('dob', models.CharField(max_length=11, null=True)),
                ('birthtime', models.CharField(max_length=255, null=True)),
                ('birthplace', models.CharField(max_length=255, null=True)),
                ('submitted', models.BooleanField(blank=True, default=False, null=True)),
                ('assigned', models.BooleanField(blank=True, default=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignSubmitReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astrologer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentor.MentorProfile')),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.UserSubmitReport')),
            ],
        ),
    ]
