# Generated by Django 2.2.14 on 2020-07-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200721_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignsubmitreport',
            name='user_report',
        ),
        migrations.AddField(
            model_name='assignsubmitreport',
            name='mentor_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MentorCallRequest'),
        ),
    ]
