# Generated by Django 2.2.14 on 2020-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200722_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='birthtime',
        ),
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersubmitdetails',
            name='submitted',
        ),
        migrations.AddField(
            model_name='assignsubmitreport',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='assignsubmitreport',
            name='pending',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='usersubmitdetails',
            name='closed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usersubmitdetails',
            name='report_submitted',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='usersubmitdetails',
            name='responded',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usersubmitdetails',
            name='scheduled',
            field=models.BooleanField(default=0),
        ),
    ]
