# Generated by Django 2.2.14 on 2020-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200722_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubmitreport',
            name='pending',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
