# Generated by Django 2.2.14 on 2020-07-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200722_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologerCareerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.MentorCallRequest')),
            ],
        ),
    ]
