# Generated by Django 2.2.14 on 2020-07-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_astrologercareerreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologercareerreport',
            name='report',
            field=models.FileField(upload_to='career_horoscope/'),
        ),
    ]
